### ISSUE TITLE
Preserving whitespace in multiline invocations?

### ISSUE THREAD

**Issue by tjgrathwell** [tjgrathwell/rails5-spec-converter#3]
Right now this multiline thingie
```
get(:show,
    project_id: project.to_param,
    id: id,
    format: :json)
```

gets converted to this
```
get(:show,
    params: { project_id: project.to_param, id: id }, format: :json)
```

which is not the worst, but not the best.

Doing anything more complicated probably requires some fancier string wrangling, and also deciding exactly what the outcome should be:

One option:
```
get(:show,
    params: {
      project_id: project.to_param,
      id: id
    },
    format: :json)
```
(the amount of indendation inside the 'params' hash would probably need to be configurable)

**Comment by connorshea** [comment]
This would be awesome if it's reasonably possible! Might want to look to Rubocop's autocorrect for inspiration?

**Comment by tjgrathwell** [comment]
Okay, it should do the thing that way now.

The output **looks** okay to me, so hopefully the extra whitespace did not introduce some subtle problem! ⚡
